import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('composes a saved figure and inspects parcels without changing its framing', async ({ page }, testInfo) => {
  test.setTimeout(120000);
  await page.setViewportSize({ width: 1700, height: 1200 });
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/demo/index.html?scenario=atlas-illustration&atlas=schaefer400-7');
  await expect(page.locator('.atlas-sheet[data-ready="true"]')).toBeVisible({ timeout: 60000 });
  const lateral = page.locator('[data-view="lateral"]');
  const names = lateral.locator('.atlas-labels text');
  const overviewIds = await names.evaluateAll(nodes => nodes.map(node => node.getAttribute('data-parcel-id')));
  await page.getByLabel('Move & pin labels').check();
  const label = names.first(), id = await label.getAttribute('data-parcel-id');
  const originalX = Number(await label.getAttribute('x'));
  await label.scrollIntoViewIfNeeded();
  const box = (await label.boundingBox())!;
  const unitsPerPixel = await lateral.locator('svg').evaluate(svg => 1200 / svg.getBoundingClientRect().width);
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 24, box.y + box.height / 2 + 12, { steps: 5 }); await page.mouse.up();
  const moved = lateral.locator(`.atlas-labels text[data-parcel-id="${id}"]`);
  await expect(moved).toHaveAttribute('data-pinned', 'true');
  expect(Number(await moved.getAttribute('x'))).toBeCloseTo(originalX + 24 * unitsPerPixel, 2);
  const pinnedX = await moved.getAttribute('x'), pinnedY = await moved.getAttribute('y');
  await expect(page.locator('#atlas-composer-status')).toHaveText('1 pinned labels');
  await page.getByLabel('Region fills').selectOption('values');
  expect(await moved.getAttribute('x')).toBe(pinnedX);
  await page.getByLabel('Border smoothing').fill('2');
  await page.getByLabel('Border smoothing').dispatchEvent('change');
  expect(await moved.getAttribute('y')).toBe(pinnedY);
  const geometry = await lateral.locator('.atlas-regions path').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')));
  await page.getByLabel('Figure title').fill('Schaefer 400 · network architecture');
  await page.getByLabel('Panel arrangement').selectOption('2');
  const saved = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Save layout', exact: true }).click();
  const layoutText = await readFile((await (await saved).path())!, 'utf8');
  const layout = JSON.parse(layoutText);
  expect(layout.columns).toBe(2); expect(layout.panels[0].layout.labels).toHaveLength(1);
  await page.getByRole('button', { name: 'Reset label pins' }).click();
  await expect(lateral.locator('text[data-pinned="true"]')).toHaveCount(0);
  await page.getByLabel('Panel arrangement').selectOption('1');
  await page.locator('#atlas-layout-file').setInputFiles({ name: 'layout.json', mimeType: 'application/json', buffer: Buffer.from(layoutText) });
  await expect(page.getByLabel('Panel arrangement')).toHaveValue('2');
  await expect(moved).toHaveAttribute('x', pinnedX!);
  const invalid = JSON.parse(layoutText); invalid.panels[1].layout.plateKey = 'another atlas'; invalid.title = 'Should not apply';
  await page.locator('#atlas-layout-file').setInputFiles({ name: 'wrong.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(invalid)) });
  await expect(page.locator('#atlas-composer-status')).toContainText('different atlas');
  await expect(page.getByLabel('Figure title')).toHaveValue(layout.title);
  await expect(moved).toHaveAttribute('x', pinnedX!);

  await page.getByLabel('Move & pin labels').uncheck();
  await page.getByLabel('Panel arrangement').selectOption('1');
  await page.getByRole('button', { name: 'Zoom in lateral', exact: true }).click();
  await expect(lateral.locator('.surfview-atlas-plate')).toHaveAttribute('data-zoom', '2');
  const detailedIds = await names.evaluateAll(nodes => nodes.map(node => node.getAttribute('data-parcel-id')));
  expect(detailedIds.some(id => !overviewIds.includes(id))).toBe(true);
  const beforePan = await lateral.locator('svg').getAttribute('viewBox');
  await lateral.locator('svg').scrollIntoViewIfNeeded();
  const viewportBox = (await lateral.locator('svg').boundingBox())!;
  await page.mouse.move(viewportBox.x + 150, viewportBox.y + 120);
  await page.mouse.down(); await page.mouse.move(viewportBox.x + 210, viewportBox.y + 140, { steps: 4 }); await page.mouse.up();
  expect(await lateral.locator('svg').getAttribute('viewBox')).not.toBe(beforePan);
  // Figure export uses the overview despite live pan/zoom, and keeps pinned text.
  await page.getByLabel('Region fills').selectOption('muted');
  await page.getByLabel('Panel arrangement').selectOption('2');
  const exported = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export complete figure · SVG' }).click();
  const svg = await readFile((await (await exported).path())!, 'utf8');
  expect(svg.match(/viewBox="0 0 1200 850"/g)).toHaveLength(2);
  expect(svg).toContain('network architecture'); expect(svg).toContain('Visual');
  expect(svg).toContain(`x="${pinnedX}" y="${pinnedY}"`);
  expect(svg).not.toMatch(/<(?:script|image|foreignObject)\b/);
  const small = await lateral.locator('metadata').evaluate(el => JSON.parse(el.textContent!).unlabeledParcelIds[0]);
  await page.getByLabel('Find a region').selectOption({ value: String(small) });
  const frame = await lateral.locator('svg').getAttribute('viewBox');
  await page.getByRole('button', { name: 'Inspect selected region' }).click();
  await expect(page.locator('.atlas-focus')).toBeVisible();
  await expect(page.locator('.atlas-focus h2')).toContainText(String(small));
  const readable = await page.locator('.atlas-focus .atlas-labels').evaluate(group => {
    const font = Number(group.getAttribute('font-size'));
    const scale = (group as SVGGraphicsElement).getScreenCTM()!.a;
    return font * scale;
  });
  expect(readable).toBeGreaterThanOrEqual(11.9);
  expect(await lateral.locator('svg').getAttribute('viewBox')).toBe(frame);
  await page.screenshot({ path: testInfo.outputPath('atlas-composer-detail.png'), fullPage: true });
  await page.getByRole('button', { name: 'Close region detail' }).click();
  await expect(page.locator('.atlas-focus .surfview-atlas-plate')).toHaveCount(0);
  expect(await lateral.locator('.atlas-regions path').evaluateAll(nodes => nodes.map(node => node.getAttribute('d')))).toEqual(geometry);
  expect(errors).toEqual([]);
});

test('Glasser plates retain labels while recoloring, synchronize selection, and export the displayed style', async ({ page }, testInfo) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/demo/index.html?scenario=atlas-illustration');
  await expect(page.locator('.atlas-sheet[data-ready="true"]')).toBeVisible({ timeout: 60000 });
  const labels = page.locator('.atlas-labels text');
  expect(await labels.count()).toBeGreaterThan(120);
  const positions = () => labels.evaluateAll(elements => elements.map(el => ({
    text: el.textContent, x: el.getAttribute('x'), y: el.getAttribute('y')
  })));
  const original = await positions();
  await page.screenshot({ path: testInfo.outputPath('atlas-highlights.png'), fullPage: true });
  await page.getByLabel('Region fills').selectOption('values');
  await page.getByLabel('Value colormap').selectOption('RdBu');
  expect(await positions()).toEqual(original);
  await page.getByLabel('Find a region').selectOption({ value: '1' });
  await expect(page.locator('#atlas-selected-name')).toHaveText('V1');
  await page.getByLabel('Custom fill', { exact: true }).fill('#18394f');
  await page.getByRole('button', { name: 'Color selected', exact: true }).click();
  const medial = page.locator('[data-view="medial"]');
  await expect(medial.locator('g[data-parcel-id="1"] > path')).toHaveAttribute('fill', '#18394f');
  await expect(medial.locator('text[data-parcel-id="1"]')).toHaveAttribute('fill', '#ffffff');
  expect(await positions()).toEqual(original);
  await page.getByLabel('Label layout').selectOption('all');
  expect(await labels.count()).toBeGreaterThan(original.length);
  await page.getByLabel('Label layout').selectOption('balanced');
  expect(await positions()).toEqual(original);
  await medial.locator('.atlas-labels text').filter({ hasText: /^V2$/ }).click();
  await expect(page.locator('#atlas-selected-name')).toHaveText('V2');
  const selected = page.locator('g[data-parcel-id="4"]');
  for (const item of await selected.all()) await expect(item).toHaveAttribute('aria-pressed', 'true');
  await page.getByLabel('Show region names').uncheck();
  await expect(labels).toHaveCount(0);
  await page.getByLabel('Show region names').check();
  expect(await positions()).toEqual(original);
  await page.getByLabel('Boundary style').selectOption('halo');
  await expect(page.locator('.atlas-boundary-halo')).toHaveCount(2);
  await page.getByLabel('Boundary style').selectOption('fine');
  await expect(page.locator('.atlas-boundary-halo')).toHaveCount(0);
  await expect(page.locator('.atlas-figure path[stroke-dasharray]')).toHaveCount(0);

  const svgDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export medial SVG' }).click();
  const svgFile = await svgDownload;
  const svg = await readFile((await svgFile.path())!, 'utf8');
  expect(svg).toContain('#18394f');
  expect(svg).toContain('>V1</text>');
  expect(svg).not.toMatch(/<(?:image|script|foreignObject)\b/);
  expect(svg).not.toContain('stroke-dasharray');
  const pngDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export medial PNG' }).click();
  const png = await readFile((await (await pngDownload).path())!);
  expect(png.subarray(1, 4).toString()).toBe('PNG');
  expect(png.readUInt32BE(16)).toBe(3600);
  expect(png.readUInt32BE(20)).toBe(2550);
  await page.screenshot({ path: testInfo.outputPath('atlas-values.png'), fullPage: true });
  await page.setViewportSize({ width: 720, height: 1000 });
  expect(await positions()).toEqual(original);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
});

test('Schaefer 400 reuses the renderer with both network tables and configurable smoothing', async ({ page }, testInfo) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/demo/index.html?scenario=atlas-illustration&atlas=schaefer400-7');
  await expect(page.locator('.atlas-sheet[data-ready="true"]')).toBeVisible({ timeout: 60000 });
  const regions = page.locator('.atlas-regions g');
  const labels = page.locator('.atlas-labels text');
  // Balanced layout intentionally omits long callouts. Most visible parcels
  // should still be labeled, and every omitted ID must remain accounted for.
  for (const svg of await page.locator('.surfview-atlas-plate svg').all()) {
    const coverage = await svg.evaluate(element => {
      const visible = [...element.querySelectorAll('.atlas-regions g')].map(p => Number(p.getAttribute('data-parcel-id')));
      const labeled = [...element.querySelectorAll('.atlas-labels text')].map(p => Number(p.getAttribute('data-parcel-id')));
      const omitted = JSON.parse(element.querySelector('metadata')!.textContent!).unlabeledParcelIds as number[];
      return { visible, labeled, omitted };
    });
    expect(coverage.labeled.length).toBeGreaterThan(coverage.visible.length / 2);
    expect([...coverage.labeled, ...coverage.omitted].sort((a, b) => a - b)).toEqual(coverage.visible.sort((a, b) => a - b));
  }
  await expect(page.getByLabel('Find a region').locator('option')).toHaveCount(201);
  const positions = () => labels.evaluateAll(elements => elements.map(el => [el.textContent, el.getAttribute('x'), el.getAttribute('y')]));
  const original = await positions();
  await expect(page.getByLabel('Region fills')).toHaveValue('muted');
  await page.getByLabel('Label layout').selectOption('all');
  expect(await labels.count()).toBeGreaterThan(original.length);
  await page.getByLabel('Label layout').selectOption('balanced');
  expect(await positions()).toEqual(original);
  await expect(page.locator('.atlas-network-legend > span')).toHaveCount(7);
  await expect(page.locator('.atlas-boundary-halo')).toHaveCount(0);
  await expect(page.locator('.atlas-group-boundaries')).toHaveCount(2);
  const groupPaths = await page.locator('.atlas-group-boundaries').evaluateAll(paths => paths.map(p => p.getAttribute('d')));
  const mutedFill = await page.locator('[data-view="lateral"] .atlas-regions g[data-parcel-id="8"] path').getAttribute('fill');
  await page.getByLabel('Region fills').selectOption('atlas');
  expect(await page.locator('[data-view="lateral"] .atlas-regions g[data-parcel-id="8"] path').getAttribute('fill')).not.toBe(mutedFill);
  expect(await page.locator('.atlas-group-boundaries').evaluateAll(paths => paths.map(p => p.getAttribute('d')))).toEqual(groupPaths);
  expect(await positions()).toEqual(original);
  await page.getByLabel('Region fills').selectOption('muted');
  await page.getByLabel('Emphasize network boundaries').uncheck();
  await expect(page.locator('.atlas-group-boundaries')).toHaveCount(0);
  await page.getByLabel('Emphasize network boundaries').check();
  expect(await page.locator('.atlas-group-boundaries').evaluateAll(paths => paths.map(p => p.getAttribute('d')))).toEqual(groupPaths);
  const ids = await regions.evaluateAll(elements => elements.map(el => el.getAttribute('data-parcel-id')));
  const paths = () => page.locator('.atlas-regions path').evaluateAll(elements => elements.map(el => el.getAttribute('d')));
  const smoothPaths = await paths();
  expect(smoothPaths.some(path => path!.includes('Q'))).toBe(true);
  const smoothing = page.locator('#atlas-smoothing');
  for (const value of ['0', '8', '4']) {
    await smoothing.fill(value);
    await smoothing.dispatchEvent('change');
    const current = await paths();
    expect(current.some(path => path!.includes('Q'))).toBe(value !== '0');
    if (value === '4') expect(current).toEqual(smoothPaths);
    else expect(current).not.toEqual(smoothPaths);
    expect(await positions()).toEqual(original);
    expect(await regions.evaluateAll(elements => elements.map(el => el.getAttribute('data-parcel-id')))).toEqual(ids);
  }
  await page.getByLabel('Find a region').selectOption({ value: '8' });
  await expect(page.locator('#atlas-selected-name')).toHaveText('7Networks_LH_Vis_8');
  await page.getByLabel('Custom fill', { exact: true }).fill('#163d52');
  await page.getByRole('button', { name: 'Color selected', exact: true }).click();
  await expect(page.locator('[data-view="lateral"] .atlas-regions g[data-parcel-id="8"] path')).toHaveAttribute('fill', '#163d52');
  const label = page.locator('[data-view="lateral"] .atlas-labels text[data-parcel-id="8"]');
  await expect(label).toHaveText('8');
  await expect(label.locator('..').locator('title')).toHaveText('7Networks_LH_Vis_8');
  expect(await positions()).toEqual(original);
  await page.getByLabel('Parcellation', { exact: true }).selectOption('schaefer400-17');
  await expect(page.locator('#atlas-selected-name')).toHaveText('Explore a region');
  await expect(page.getByLabel('Find a region')).toHaveValue('');
  await expect(page.getByLabel('Find a region').locator('option')).toHaveCount(201);
  await page.getByLabel('Find a region').selectOption({ value: '1' });
  await expect(page.locator('#atlas-selected-name')).toHaveText('17Networks_LH_VisCent_ExStr_1');
  await page.getByLabel('Label text', { exact: true }).selectOption('names');
  const names = await labels.allTextContents();
  expect(names.length).toBeGreaterThan(0);
  expect(names.every(name => name.startsWith('17Networks_LH_'))).toBe(true);
  await page.getByLabel('Label text', { exact: true }).selectOption('ids');
  const downloaded = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export medial SVG' }).click();
  const file = await downloaded;
  expect(file.suggestedFilename()).toBe('schaefer400-17-left-medial.svg');
  const svg = await readFile((await file.path())!, 'utf8');
  expect(svg).toContain('schaefer400-17-left-fslr32k');
  expect(svg).toContain('17Networks_LH_VisCent_ExStr_1');
  expect(svg).not.toContain('#163d52');
  await page.screenshot({ path: testInfo.outputPath('schaefer400-17.png'), fullPage: true });
  expect(errors).toEqual([]);
});
