export const mapLabStyles = `
.parcel-map-lab{display:grid;grid-template-columns:minmax(0,1fr) 306px;gap:24px;color:#263d49;font:13px/1.45 system-ui,-apple-system,sans-serif;min-width:0}
.parcel-map-lab *{box-sizing:border-box}.parcel-map-lab [hidden]{display:none!important}
.parcel-map-lab button,.parcel-map-lab select{font:inherit;color:inherit;border:1px solid #bac9cf;border-radius:6px;background:#fff;padding:7px 9px;cursor:pointer}
.parcel-map-lab button:hover{background:#edf3f5}.parcel-map-lab button:focus-visible,.parcel-map-lab select:focus-visible,.parcel-map-lab input:focus-visible{outline:2px solid #317d91;outline-offset:2px}
.pml-main{min-width:0}.pml-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:14px}.pml-metrics>div{padding:12px 14px;background:#fafcfc;border-radius:9px}.pml-metrics span{display:block;font-size:11px;color:#5d707b}.pml-metrics strong{font-size:23px;display:block;font-weight:550;font-variant-numeric:tabular-nums}
.pml-stage{position:relative;height:calc(100vh - 345px);min-height:420px;background:#f4f6f6;border-radius:12px;overflow:hidden}.pml-stage>canvas{display:block;width:100%;height:100%;touch-action:manipulation}
.pml-legend{position:absolute;bottom:10px;left:14px;right:14px;text-align:center;font-size:11px;color:#536976;pointer-events:none}.pml-tooltip{position:absolute;pointer-events:none;max-width:224px;padding:6px 9px;border-radius:6px;color:#fff;background:#253c4aed;z-index:4;font-size:12px}
.pml-loading{position:absolute;inset:0;display:grid;place-items:center;padding:40px;text-align:center;background:#f4f6f6f5}
.pml-state{min-height:38px;padding:10px 2px;font-size:12px;color:#526b78}.pml-comparison-heading{display:flex;justify-content:space-between;align-items:center;margin:4px 0 8px}.pml-comparison-heading h3{margin:0;font-size:14px}.pml-comparisons{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.pml-comparisons>p{grid-column:1/-1;color:#536976}.pml-snapshot{display:grid;gap:3px;text-align:left;padding:6px!important;min-width:0}.pml-snapshot img{width:100%;height:92px;object-fit:contain;background:#f4f6f6}.pml-snapshot strong{font-weight:550;font-size:12px}.pml-snapshot span{font-size:10px;color:#526b78}
.pml-controls{max-height:calc(100vh - 108px);overflow-y:auto;padding:0 10px 15px 0;display:grid;align-content:start;gap:13px}.pml-controls h2{margin:0;font-size:18px;font-weight:600}.pml-controls h3{margin:9px 0 0;font-size:13px;font-weight:650}.pml-controls label{display:grid;gap:5px;position:relative;min-width:0}.pml-controls label>select{width:100%;min-width:0}.pml-controls output{float:right;position:absolute;right:0;top:0;color:#537484;font-size:11px;font-variant-numeric:tabular-nums}.pml-controls input[type=range]{width:100%;accent-color:#558c9b;margin:2px 0}.pml-controls .pml-check{display:flex;align-items:center;font-size:12px}.pml-check input{accent-color:#558c9b}.pml-two{display:grid;grid-template-columns:1.1fr 1fr;gap:10px}.pml-two output{position:static;float:none;display:inline}.pml-range-labels{display:flex;justify-content:space-between;font-size:10px;color:#647d88}.pml-hint{font-size:11px;line-height:1.5;color:#5c7582;margin:0}.pml-buttons{display:flex;flex-wrap:wrap;gap:6px}.pml-buttons [data-optimize]{background:#dce9ec;border-color:#91adb7}.pml-controls details{font-size:11px;color:#58717e}.pml-controls summary{cursor:pointer}.pml-detail{position:absolute;left:16px;top:16px;width:236px;background:#ffffffed;padding:14px;border-radius:10px;box-shadow:0 8px 32px #29424d25;z-index:3}.pml-detail h3{margin:5px 0 8px;font-size:14px;overflow-wrap:anywhere;padding-right:16px}.pml-detail small{font-size:10px;color:#627883}.pml-detail [data-close-detail]{position:absolute;right:8px;top:7px;border:0;background:transparent;font-size:20px;padding:0 4px}.pml-detail [data-preview]{height:158px;border-radius:6px;overflow:hidden}.pml-detail [data-preview] canvas{display:block;touch-action:none}.pml-detail [data-detail-values]{font-size:11px;margin-top:8px}.pml-detail p{font-size:10px;margin:7px 0 0;color:#647883}
@media(max-width:1050px){.parcel-map-lab{grid-template-columns:minmax(0,1fr) 275px;gap:16px}.pml-metrics{gap:5px}.pml-metrics>div{padding:8px}.pml-metrics strong{font-size:20px}.pml-metrics span{font-size:10px}}
@media(max-width:760px){.parcel-map-lab{grid-template-columns:minmax(0,1fr)}.pml-controls{max-height:none;overflow:visible;padding:0}.pml-stage{height:430px;min-height:360px}.pml-metrics{grid-template-columns:repeat(2,1fr)}.pml-metrics strong{font-size:22px}.pml-metrics span{font-size:11px}.pml-comparisons{grid-template-columns:repeat(2,minmax(0,1fr))}.pml-detail{width:210px}.pml-detail [data-preview]{height:158px}}
`;
